# Dockerfile for alpine-based forwarder

FROM ubuntu

# Set timezone so install does not request it interactively
# which doesnt work from docker build
ENV DEBIAN_FRONTEND noninteractive


RUN apk update
# RUN apk add  python2
# RUN apk add -y python2-pip
RUN apk add  mosquitto-clients

COPY py/imgproc.py /bin/imgproc.py

# RUN pip install numpy
# RUN pip install Pillow
# RUN pip install paho-mqtt

CMD ash
# CMD python2 /bin/mqttforwarder.py
